### ISSUE TITLE
关于多标签页的，有个问题想问一下

### ISSUE THREAD

**Issue by lanweifeng** [houjunjie/Mini-Program#1]
你好，冒昧打扰，我在[https://github.com/kuhami/react-ant/issues/13](url)上看到你有跟帖回复怎么解决ract多标签切换重复渲染的问题，回帖上写着用Route的children方法加载组件就不会重复渲染，我查了下children是一个函数，但是不知道函数里面具体要写哪些，能否指教下，万分感谢。
我目前的写法：
`openPages.map(page => (

                      <TabPane forceRender tab={page.name} key={page.path}>
                        <Route key={page.path} component={page.component} exact={false} />
                      </TabPane>
                    ))`

如何替换component？

**Comment by houjunjie** [comment]
`
<TabPane forceRender tab={page.name} key={page.path}>
      <Route key={page.path} children={page.component} exact={false} />
</TabPane>
`
我的是这样的。把component换成了children

**Comment by houjunjie** [comment]
@lanweifeng
